Update run-script.yml

diff --git a/.github/workflows/run-script.yml b/.github/workflows/run-script.yml
--- a/.github/workflows/run-script.yml
+++ b/.github/workflows/run-script.yml
@@ -23,3 +23,12 @@ jobs:
 
       - name: Run script
         run: python jsonGen.py # Replace with your actual file name
+    
+      - name: Commit and push changes
+        run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+        git add .
+        # The '|| true' prevents the workflow from failing if there are no changes to commit
+        git commit -m "Automated file update" || echo "No changes to commit"
+        git push
